### ISSUE TITLE
AttributeError: module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by hivam** [OCA/bank-statement-import#406] opened 2021-08-12 00:31 UTC
When trying to import a file, the system generates the following error in the user interface: 

_Something went wrong !_

_Could not make sense of the given file._
_Did you install the module to support this type of file ?_

When checking the log I see this error:

**AttributeError: module 'time' has no attribute 'clock'**

In the odoo forum they indicate that it is a depreciated library:

_The function time.clock() has been removed, after having been deprecated since Python 3.3: use time.perf_counter() or time.process_time() instead, depending on your requirements, to have well-defined behavior_ [1]

**Is there any way to solve the problem?**

[1] https://www.odoo.com/es_ES/forum/ayuda-1/attributeerror-module-time-has-no-attribute-clock-183827

**Comment by pedrobaeza** [comment] 2021-08-12 06:51
Which module of this repo? Which Odoo version?

**Comment by hivam** [comment] 2021-08-12 19:26
**Module**: account_bank_statement_import_txt_xlsx
**Odoo**: v13 C.E.

**Comment by pedrobaeza** [comment] 2021-08-12 22:32
You have an incorrect deployment or other custom module, as this module is not using such method. Closing as no issue of this repo.

**Closed as completed by pedrobaeza** 2021-08-12 22:32 UTC

**Comment by bodedra** [comment] 2021-08-12 22:37
@pedrobaeza Module name is correct. I can found it. I haven't reproduce it because don't have enough steps.

v13 Module ref: https://github.com/OCA/bank-statement-import/tree/13.0/account_bank_statement_import_txt_xlsx

**Comment by pedrobaeza** [comment] 2021-08-12 22:39
I'm not saying the module name is incorrect. Please read again my explanation.

**Comment by bodedra** [comment] 2021-08-12 22:43
Got it. You are correct. I validate module code and haven't found any evidence related to the reported issue.
